"""Initial migration: all tables

Revision ID: 347d2ff67401
Revises: 
Create Date: 2025-12-05 13:36:01.154225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347d2ff67401'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_telegram_id'), 'access_requests', ['telegram_id'], unique=False)
    op.create_table('sniper_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('filters_limit', sa.Integer(), nullable=False),
    sa.Column('notifications_limit', sa.Integer(), nullable=False),
    sa.Column('notifications_sent_today', sa.Integer(), nullable=False),
    sa.Column('last_notification_reset', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sniper_users_telegram_id'), 'sniper_users', ['telegram_id'], unique=True)
    op.create_table('tender_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_number', sa.String(length=100), nullable=False),
    sa.Column('tender_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('times_matched', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_cache_tender_number'), 'tender_cache', ['tender_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('sniper_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('exclude_keywords', sa.JSON(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('customer_types', sa.JSON(), nullable=True),
    sa.Column('tender_types', sa.JSON(), nullable=True),
    sa.Column('law_type', sa.String(length=50), nullable=True),
    sa.Column('purchase_stage', sa.String(length=100), nullable=True),
    sa.Column('purchase_method', sa.String(length=100), nullable=True),
    sa.Column('okpd2_codes', sa.JSON(), nullable=True),
    sa.Column('min_deadline_days', sa.Integer(), nullable=True),
    sa.Column('customer_keywords', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sniper_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sniper_filters_user_active', 'sniper_filters', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_sniper_filters_user_id'), 'sniper_filters', ['user_id'], unique=False)
    op.create_table('sniper_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('filter_name', sa.String(length=255), nullable=True),
    sa.Column('tender_number', sa.String(length=100), nullable=False),
    sa.Column('tender_name', sa.Text(), nullable=False),
    sa.Column('tender_price', sa.Float(), nullable=True),
    sa.Column('tender_url', sa.String(length=500), nullable=True),
    sa.Column('tender_region', sa.String(length=255), nullable=True),
    sa.Column('tender_customer', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('matched_keywords', sa.JSON(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['sniper_filters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sniper_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sniper_notifications_filter_id'), 'sniper_notifications', ['filter_id'], unique=False)
    op.create_index('ix_sniper_notifications_tender', 'sniper_notifications', ['tender_number'], unique=False)
    op.create_index(op.f('ix_sniper_notifications_tender_number'), 'sniper_notifications', ['tender_number'], unique=False)
    op.create_index(op.f('ix_sniper_notifications_user_id'), 'sniper_notifications', ['user_id'], unique=False)
    op.create_index('ix_sniper_notifications_user_sent', 'sniper_notifications', ['user_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sniper_notifications_user_sent', table_name='sniper_notifications')
    op.drop_index(op.f('ix_sniper_notifications_user_id'), table_name='sniper_notifications')
    op.drop_index(op.f('ix_sniper_notifications_tender_number'), table_name='sniper_notifications')
    op.drop_index('ix_sniper_notifications_tender', table_name='sniper_notifications')
    op.drop_index(op.f('ix_sniper_notifications_filter_id'), table_name='sniper_notifications')
    op.drop_table('sniper_notifications')
    op.drop_index(op.f('ix_sniper_filters_user_id'), table_name='sniper_filters')
    op.drop_index('ix_sniper_filters_user_active', table_name='sniper_filters')
    op.drop_table('sniper_filters')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tender_cache_tender_number'), table_name='tender_cache')
    op.drop_table('tender_cache')
    op.drop_index(op.f('ix_sniper_users_telegram_id'), table_name='sniper_users')
    op.drop_table('sniper_users')
    op.drop_index(op.f('ix_access_requests_telegram_id'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
