"""add_user_events_table

Revision ID: 93c388d2ce73
Revises: 20251224_monetization
Create Date: 2026-01-14 19:35:40.331770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c388d2ce73'
down_revision: Union[str, Sequence[str], None] = '20251224_monetization'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('broadcast_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcast_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sniper_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_events_created_at'), 'user_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_events_telegram_id'), 'user_events', ['telegram_id'], unique=False)
    op.create_index('ix_user_events_type_date', 'user_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_index('ix_user_events_user_type', 'user_events', ['user_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_events_user_type', table_name='user_events')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index('ix_user_events_type_date', table_name='user_events')
    op.drop_index(op.f('ix_user_events_telegram_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_created_at'), table_name='user_events')
    op.drop_table('user_events')
    # ### end Alembic commands ###
